name: notify-issue

  workflow_call:
    inputs:
      repository:
        description: 'Github Repository'
        required: true
        type: string    
      issue_number:
        description: 'Issue Number'
        required: true
        type: string 

jobs:
  issue:
    runs-on: ubuntu-latest
    name: New Issue Notification
    steps:
      - uses: mattermost/action-mattermost-notify@2.0.0
        with:
          MATTERMOST_WEBHOOK_URL: ${{ secrets.MATTERMOST_WEBHOOK_URL }}
          MATTERMOST_USERNAME: ${{ secrets.MATTERMOST_USERNAME}}
          MATTERMOST_ICON_URL: ${{ secrets.MATTERMOST_ICON }}
          TEXT: "${{ inputs.repository }}: New Issue https://github.com/${{ inputs.repository }}/issues/${{ inputs.issue_number }}"
