name: notify-pr
on:
  workflow_call:
    inputs:
      repository:
        description: 'Github Repository'
        required: true
        type: string    
      pr_number:
        description: 'Pull Request Number'
        required: true
        type: string            
  
jobs:
  pr:
    runs-on: ubuntu-latest
    name: Pull Request Notification
    steps:
      - uses: mattermost/action-mattermost-notify@2.0.0
        with:
          MATTERMOST_WEBHOOK_URL: ${{ secrets.MATTERMOST_WEBHOOK_URL }}
          MATTERMOST_USERNAME: ${{ secrets.MATTERMOST_USERNAME}}
          MATTERMOST_ICON_URL: ${{ secrets.MATTERMOST_ICON }}
          TEXT: "${{ inputs.repository }} : PR https://github.com/${{ inputs.repository }}/pull/${{ inputs.pr_number }}"
